### ISSUE TITLE
Can't connect to a DB with auth

### ISSUE THREAD

**Issue by poohitan** [ishanjain28/s3-mongo-backup#10]
Hi, I've been using this module for a long time already.
After I enabled authorization for my database using username and password, things has broke down.
When trying to make a backup I get this error:

>Command failed: mongodump -h localhost -d %db_name& -p %password% -u %username% --gzip --archive=/var/folders/r5/q00t2fw54nq48jtgrjwnl5tm0000gn/T/%db_name%_2017-12-15T18-28-13.gz
>Failed: error connecting to db server: server returned error on SASL authentication step: Authentication failed.

As I've investigated, the problem it that the user I'm connecting with is stored in `admin` database which is not the default database for storing users. In such cases the connection should be set up with an extra param `--authenticationDatabase %db_name%` (in my case `--authenticationDatabase "admin"`).

I've tested it by using the underlying `mongodump` command (which I saw in the error message above) with  `--authenticationDatabase "admin"` and it worked well.

So it would be great to make it possible to pass `authenticationDatabase` param to make it work when users are stored in a non-default database.

More related info here 
- https://docs.mongodb.com/manual/tutorial/enable-authentication/
- https://stackoverflow.com/questions/38744131/server-returned-error-on-sasl-authentication-step-authentication-failed

**Comment by brycelund** [comment]
#16

**Comment by ishanjain28** [comment]
Thanks to @brycelund this issue has been fixed.
