### ISSUE TITLE
Restore from a backup

### ISSUE THREAD

**Issue by poohitan** [ishanjain28/s3-mongo-backup#7]
First of all thanks for this module.

I have problems with restoring from backups and can't find any docs on it. Can you please add a sample command to readme?

I've tried two commands:

1. `mongorestore --nsInclude 'mydb.*' --gzip --archive=mongodumps/mydb_2017-07-02T10-00-01.gz`
– it fails with error: `Failed: unexpected EOF`
2. `mongorestore --gzip mongodumps/` which fails with `don't know what to do with file "mongodumps/mydb_2017-07-02T10-00-01.gz", skipping...`

Appreciate your help.

**Comment by poohitan** [comment]
Actually the first command works fine, `EOF` error was my mistake.

Anyway, I think it would be great to add a sample of restoring DB from backup in Readme for those, who is not familiar with `mongorestore` yet.

**Comment by ishanjain28** [comment]
First of all, Thank you for taking the time to create an issue and Apologies for not replying quickly, I was out on a vacation. 

I had plans to create a s3-mongo-restore module but then I just got busy with other projects. I'll add an example and start working on [s3-mongo-restore](https://github.com/ishanjain28/s3-mongo-restore) from today.

**Comment by poohitan** [comment]
@ishanjain28 thank you! Good luck 👍

**Comment by ishanjain28** [comment]
@poohitan It's a bit late now, But I figured it would be a good idea to inform you that I've published a new module that helps in restoring backups, It's [here](https://npm.im/s3-mongo-restore)

**Comment by poohitan** [comment]
@ishanjain28 cool! thank you.
