### ISSUE TITLE
ECMAScript 6 Issues in backup.js

### ISSUE THREAD

**Issue by ripal-pm** [ishanjain28/s3-mongo-backup#8]
Hi Ishan,

I am encountering below issues:

1. It requires 'use strict'; at the top of the file.
2. Object de-structuring is failing.
`const {database, password, username} = config.mongodb, {timezoneOffset} = config,
            host = config.mongodb.hosts[0].host,
            port = config.mongodb.hosts[0].port;`

If you can replace that with:
`const database = config.mongodb.database, 
            password = config.mongodb.password || undefined,
            username = config.mongodb.username || undefined, 
            timezoneOffset = config.timezoneOffset,
            host = config.mongodb.hosts[0].host,
            port = config.mongodb.hosts[0].port;`

`const {bucketName, accessPerm, region} = config.s3;`

If you can replace that with:
`const bucketName = config.s3.bucketName,
        accessPerm = config.s3.accessPerm,
        region = config.s3.region;`

Please let me know if you have any questions.

Thanks!

**Comment by ishanjain28** [comment]
Sure. I'll do that. :+1:

**Comment by ripal-pm** [comment]
Thanks for quick response, Ishan.

**Comment by ishanjain28** [comment]
Sorry, about the delay.

**Comment by ripal-pm** [comment]
I did great job. Please don't be sorry!

**Comment by ripal-pm** [comment]
You did great job. Please don't be sorry.

**Comment by ishanjain28** [comment]
@ripal-pm This [commit](https://github.com/ishanjain28/s3-mongo-backup/commit/ecd27552d9caef023d12633f36a56d7c8a40a9b4) fixes the issues you mentioned.

Version [2.0.1](http://npm.im/s3-mongo-backup) has been published on npm. 

Closing this issue now.
