### ISSUE TITLE
MongoDB query parameter

### ISSUE THREAD

**Issue by zubair1024** [ishanjain28/s3-mongo-backup#9]
Is it possible to pass in mongodb query parameter from the code? If not, can that be provisioned?

**Comment by ishanjain28** [comment]
What do you mean by "Mongodb query parameter"? I am not sure if I understand your issue.

**Comment by zubair1024** [comment]
I have modified your code to achieve that:

` 
       // Default command, does not considers username or password
        let command = `mongodump -h ${host} --port=${port} -d ${database} --gzip --archive=${BACKUP_PATH(DB_BACKUP_NAME)}`;

        // When Username and password is provided
        if (username && password) {
            command = `mongodump -h ${host} --port=${port} -d ${database} -p ${password} -u ${username} --gzip --archive=${BACKUP_PATH(DB_BACKUP_NAME)}`;
        }
        // When Username is provided
        if (username && !password) {
            command = `mongodump -h ${host} --port=${port} -d ${database} -u ${username} --gzip --archive=${BACKUP_PATH(DB_BACKUP_NAME)}`;
        }

        if (collection && !query) {
            DB_BACKUP_NAME = `${database}_${currentTime(timezoneOffset)}_${collection}.gz`;
            command = `mongodump -h ${host} --port=${port} -d ${database}  -p ${password} -u ${username} --collection ${collection} --gzip --archive=${BACKUP_PATH(DB_BACKUP_NAME)}`;
        }

        if (collection && query && username) {
            DB_BACKUP_NAME = `${database}_${currentTime(timezoneOffset)}_${collection}.gz`;
            command = `mongodump -h ${host} --port=${port} -d ${database}  -p ${password} -u ${username} --collection ${collection} --query ${query} --gzip --archive=${BACKUP_PATH(DB_BACKUP_NAME)}`;
        }

        if (collection && query && !username) {
            DB_BACKUP_NAME = `${database}_${currentTime(timezoneOffset)}_${collection}.gz`;
            command = `mongodump -h ${host} --port=${port} -d ${database} --collection ${collection} --query ${query} --gzip --archive=${BACKUP_PATH(DB_BACKUP_NAME)}`;
        }

`
